#!/bin/sh /etc/rc.common
# AutoLogin Daemon init script menggunakan procd

START=95
STOP=10
USE_PROCD=1

. /usr/lib/autologin/logging.sh

start_service() {
    log_info "init.d/autologin" "Memulai daemon AutoLogin..."
    procd_open_instance
    procd_set_param command /bin/sh /usr/lib/autologin/daemon.sh
    procd_set_param respawn 60 5 1
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
    log_info "init.d/autologin" "Daemon AutoLogin sudah berjalan."
}

stop_service() {
    log_info "init.d/autologin" "Menghentikan daemon dan semua proses terkait..."
    
    pkill -f '/usr/lib/autologin/daemon.sh' 2>/dev/null
    pkill -f '/usr/lib/autologin/login_executor.sh' 2>/dev/null
    pkill -f '/usr/lib/autologin/anti_blocking.sh' 2>/dev/null
    pkill -f '/usr/lib/autologin/health_check.sh' 2>/dev/null
    
    sleep 1
    
    pkill -9 -f '/usr/lib/autologin/daemon.sh' 2>/dev/null
    pkill -9 -f '/usr/lib/autologin/login_executor.sh' 2>/dev/null
    pkill -9 -f '/usr/lib/autologin/anti_blocking.sh' 2>/dev/null
    
    log_info "init.d/autologin" "Membersihkan berkas sementara..."
    rm -f /var/run/autologin_*.lock 2>/dev/null
    rm -f /tmp/autologin_cookie_* 2>/dev/null
    rm -f /tmp/autologin_mikrotik_* 2>/dev/null
    rm -f /tmp/autologin/state/*.state 2>/dev/null
    rm -f /tmp/autologin_trigger_* 2>/dev/null
    
    log_info "init.d/autologin" "Semua proses dihentikan dan berkas sementara dibersihkan."
}