# URL yang digunakan untuk probing
http://clients3.google.com/generate_204
http://www.apple.com/library/test/success.html
http://detectportal.firefox.com/canonical.html
http://www.msftconnecttest.com/connecttest.txt
http://detectportal.firefox.com/success.txt
http://www.google.com/generate_204
http://captive.apple.com/hotspot-detect.html
http://connect.rom.miui.com/generate_204
http://connectivity-check.ubuntu.com
http://ping.archlinux.org